[package]
name = "kyle-tran/run-or-get-shot"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
BezierTween = "arxkdev/beziertween@0.0.3"
Spring = "arxkdev/spring@0.0.3"
Cmdr = "evaera/cmdr@1.12.0"
CameraShaker = "encrxyptedethan/camerashaker@1.0.0"
Fusion = "elttob/fusion@0.2.0"
Loader = "sleitnick/loader@2.0.0"
RblxUtils = "raphtalia/rbxutils@1.0.0"
Red = "red-blox/red@2.3.2"
Signal = "sleitnick/signal@2.0.3"
TopbarPlus = "aspecky/topbarplus@2.9.3"
Trove = "sleitnick/trove@1.3.0"
Promise = "lukadev-0/typed-promise@4.0.2"
Reflex = "littensy/reflex@4.3.1"
Lapis = "nezuo/lapis@^0.3.3"
t = "osyrisrblx/t@3.1.1"